package cit360_examples.entity;
// Generated Oct 19, 2017 8:02:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * People generated by hbm2java
 */
public class People  implements java.io.Serializable {


     private Integer peopleId;
     private String peopleFirst;
     private String peopleLast;
     private String peopleSex;
     private Set birthdays = new HashSet(0);

    public People() {
    }

	
    public People(String peopleFirst, String peopleLast, String peopleSex) {
        this.peopleFirst = peopleFirst;
        this.peopleLast = peopleLast;
        this.peopleSex = peopleSex;
    }
    public People(String peopleFirst, String peopleLast, String peopleSex, Set birthdays) {
       this.peopleFirst = peopleFirst;
       this.peopleLast = peopleLast;
       this.peopleSex = peopleSex;
       this.birthdays = birthdays;
    }
   
    public Integer getPeopleId() {
        return this.peopleId;
    }
    
    public void setPeopleId(Integer peopleId) {
        this.peopleId = peopleId;
    }
    public String getPeopleFirst() {
        return this.peopleFirst;
    }
    
    public void setPeopleFirst(String peopleFirst) {
        this.peopleFirst = peopleFirst;
    }
    public String getPeopleLast() {
        return this.peopleLast;
    }
    
    public void setPeopleLast(String peopleLast) {
        this.peopleLast = peopleLast;
    }
    public String getPeopleSex() {
        return this.peopleSex;
    }
    
    public void setPeopleSex(String peopleSex) {
        this.peopleSex = peopleSex;
    }
    public Set getBirthdays() {
        return this.birthdays;
    }
    
    public void setBirthdays(Set birthdays) {
        this.birthdays = birthdays;
    }




}


